## Visualize intersection between different metrics on the imputed networks

### Libaraies and Data
```{r, echo=FALSE}

rm(list=ls())

library(ggplot2)
load(file="imputed_overlaps_allpcas.RData")
load("../summarize-centrality-results/resp_pcas_after_cutoffs.RData")
```

### Data matrix
```{r, echo=FALSE}
## read data
resp_norm_btwn_evcent <- resp_btwn_evcent_cutoff/length(resp_btwn_after_cutoff)
resp_norm_btwn_bridging <- resp_btwn_bridging_cutoff/length(resp_btwn_after_cutoff)
resp_norm_btwn_kp <- resp_btwn_kp_cutoff/length(resp_btwn_after_cutoff)

resp_norm_evcent_btwn <- resp_btwn_evcent_cutoff/length(resp_evcent_after_cutoff)
resp_norm_evcent_bridging <- resp_evcent_bridging_cutoff/length(resp_evcent_after_cutoff)
resp_norm_evcent_kp <- resp_evcent_kp_cutoff/length(resp_evcent_after_cutoff)

resp_norm_bridging_btwn <- resp_btwn_bridging_cutoff/length(resp_bridging_after_cutoff)
resp_norm_bridging_evcent <-resp_evcent_bridging_cutoff/length(resp_bridging_after_cutoff)
resp_norm_bridging_kp <- resp_bridging_kp_cutoff/length(resp_bridging_after_cutoff)

resp_norm_kp_btwn <- resp_btwn_kp_cutoff/length(resp_kp_after_cutoff)
resp_norm_kp_evcent <- resp_evcent_kp_cutoff/length(resp_kp_after_cutoff)
resp_norm_kp_bridging <- resp_bridging_kp_cutoff/length(resp_kp_after_cutoff)

## form matrix
   resp_cutoffs_overlap_matrix <- as.data.frame(matrix(1, nrow=4, ncol=4))
   resp_cutoffs_overlap_matrix[1, 2:4] <- c(resp_norm_btwn_evcent, resp_norm_btwn_bridging, resp_norm_btwn_kp)
   resp_cutoffs_overlap_matrix[2, c(1,3:4)] <- c(resp_norm_evcent_btwn, resp_norm_evcent_bridging, 
                                            resp_norm_evcent_kp)
   resp_cutoffs_overlap_matrix[3, c(1,2, 4)] <- c(resp_norm_bridging_btwn, resp_norm_bridging_evcent,
                                             resp_norm_bridging_kp)
   resp_cutoffs_overlap_matrix[4, c(1:3)] <- c(resp_norm_kp_btwn, resp_norm_kp_evcent,
                                             resp_norm_kp_bridging)

## view matrix
   resp_cutoffs_overlap_matrix
```

### Plot
```{r, echo=FALSE}
positions <- c(0, 0.33, 0.66, 1)
labels <- c("BT", "EV", "BR", "KP")
image(as.matrix(resp_cutoffs_overlap_matrix), col=gray(32:0/32), xaxt="n", yaxt="n")
axis(1, at=positions, labels=labels)
axis(2, at=positions, labels=labels)
#image(as.matrix(cutoffs_overlap_matrix[1:3,1:3]), col=gray(32:0/32), xaxt="n", yaxt="n")
```

```{r, echo=FALSE}
## save pdf

png(file="imputed_networks_overlaps.png")

#par(mfrow=c(2,1))

image(as.matrix(cutoffs_overlap_matrix), col=gray(32:0/32), xaxt="n", yaxt="n", 
      main="All PCA's")
axis(1, at=positions, labels=labels)
axis(2, at=positions, labels=labels)

# image(as.matrix(resp_cutoffs_overlap_matrix), col=gray(32:0/32), xaxt="n", yaxt="n",
#       main="Respondents in PCA's Only")
# axis(1, at=positions, labels=labels)
# axis(2, at=positions, labels=labels)

dev.off()
#image(as.matrix(cutoffs_overlap_matrix[1:3,1:3]), col=gray(32:0/32), xaxt="n", yaxt="n")
```