## Visualize intersection between different metrics on the imputed networks

### Libaraies and Data
```{r, echo=FALSE}

rm(list=ls())

library(ggplot2)
load("../summarize-centrality-results/pcas_after_cutoffs.RData")
```

### Data matrix
```{r, echo=FALSE}
## read data
norm_btwn_evcent <- btwn_evcent_cutoff/length(btwn_after_cutoff)
norm_btwn_bridging <- btwn_bridging_cutoff/length(btwn_after_cutoff)
norm_btwn_kp <- btwn_kp_cutoff/length(btwn_after_cutoff)

norm_evcent_btwn <- btwn_evcent_cutoff/length(evcent_after_cutoff)
norm_evcent_bridging <- evcent_bridging_cutoff/length(evcent_after_cutoff)
norm_evcent_kp <- evcent_kp_cutoff/length(evcent_after_cutoff)

norm_bridging_btwn <- btwn_bridging_cutoff/length(bridging_after_cutoff)
norm_bridging_evcent <- evcent_bridging_cutoff/length(bridging_after_cutoff)
norm_bridging_kp <- bridging_kp_cutoff/length(bridging_after_cutoff)

norm_kp_btwn <- btwn_kp_cutoff/length(kp_after_cutoff)
norm_kp_evcent <- evcent_kp_cutoff/length(kp_after_cutoff)
norm_kp_bridging <- bridging_kp_cutoff/length(kp_after_cutoff)

## form matrix
   cutoffs_overlap_matrix <- as.data.frame(matrix(1, nrow=4, ncol=4))
   cutoffs_overlap_matrix[1, 2:4] <- c(norm_btwn_evcent, norm_btwn_bridging, norm_btwn_kp)
   cutoffs_overlap_matrix[2, c(1,3:4)] <- c(norm_evcent_btwn, norm_evcent_bridging, 
                                            norm_evcent_kp)
   cutoffs_overlap_matrix[3, c(1,2, 4)] <- c(norm_bridging_btwn, norm_bridging_evcent,
                                             norm_bridging_kp)
   cutoffs_overlap_matrix[4, c(1:3)] <- c(norm_kp_btwn, norm_kp_evcent,
                                             norm_kp_bridging)

## view matrix
   cutoffs_overlap_matrix
```

### Plot
```{r, echo=FALSE}
positions <- c(0, 0.33, 0.66, 1)
labels <- c("BT", "EV", "BR", "KP")
image(as.matrix(cutoffs_overlap_matrix), col=gray(32:0/32), xaxt="n", yaxt="n")
axis(1, at=positions, labels=labels)
axis(2, at=positions, labels=labels)
#image(as.matrix(cutoffs_overlap_matrix[1:3,1:3]), col=gray(32:0/32), xaxt="n", yaxt="n")

png(file="imputed_networks_overlaps_all_sPCAs.png")
image(as.matrix(cutoffs_overlap_matrix), col=gray(32:0/32), xaxt="n", yaxt="n")
axis(1, at=positions, labels=labels)
axis(2, at=positions, labels=labels)
dev.off()
```

```{r, echo=FALSE}
## save
save.image(file="imputed_overlaps_allpcas.RData")
```
